version: '3.9'

services:
  raft-api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
      - '2112:2112'
    depends_on:
      - prometheus
      - grafana
      - redis

  prometheus:
    image: prom/prometheus:v2.30.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana

  redis:
    image: redis:7.0.5-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  prometheus-data:
  grafana-data:
  redis-data: